<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>AIAgentDemo.Web</RootNamespace>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>aiagentdemo-web-5b0f7c1e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AIAgentDemo.Core\AIAgentDemo.Core.csproj" />
  </ItemGroup>

</Project>
